version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Install Docker client
          command: apt-get install -y docker-cli
      - run:
          name: Setting up test environment
          command: bin/runDgraph.sh
      - run:
          name: Test
          command: npm test
      - run:
          name: Starting server
          command: npm run start:dev
          background: true
      - run:
          name: Waiting for the server
          command: sleep 5
      - run:
          name: Diffing GraphQL schema
          command: npm run schema:check
      - run:
          name: Publishing GraphQL schema
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run schema:publish
            fi
